<?php

class Trtrainingtrainers_Model_TrTrainingTrainersView extends MyIndo_Db_Table_Abstract
{
	protected $_name = 'TR_TRAINING_TRAINERS_VIEW';
	protected $_primary = array(
		'ID',
		'TR_TRAININGS_ID',
		'TRAINER_ID',
		'ROLE_ID',
		'CITY_ID',
		'PROVINCE_ID',
		'COUNTRY_ID',
		'TRAINING_USER_ID',
		'TRAINING_ID',
		'TRAINING_AREA_LEVEL_ID',
		'TRAINING_BENEFICIARIES_ID',
		'TRAINING_FUNDING_SOURCE_ID',
		'TRAINING_VENUE_ID',
		'TRAINING_ORGANIZATION_ID',
		'TRAINING_FUNDING_SOURCE_CITY_ID',
		'TRAINING_FUNDING_SOURCE_PROVINCE_ID',
		'TRAINING_FUNDING_SOURCE_COUNTRY_ID',
		'TRAINING_VENUE_CITY_ID',
		'TRAINING_VENUE_PROVINCE_ID',
		'TRAINING_VENUE_COUNTRY_ID',
		'TRAINING_ORGANIZATION_CITY_ID',
		'TRAINING_ORGANIZATION_PROVINCE_ID',
		'TRAINING_ORGANIZATION_COUNTRY_ID'
		);
}