<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<title>Training M&amp;E Database System</title>
		<!-- Start : CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl('bootstrap.css')?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/style.css')?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/icons.css')?>" type="text/css" />
		<!-- End of : CSS -->
		<!-- Start : JS -->
		<script type="text/javascript" src="<?php echo $this->baseUrl('vendor/extjs/ext-all.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/MyIndo.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/MyProject.js')?>"></script>
		<script type="text/javascript">
			MyIndo.setBaseUrl('<?php echo $this->baseUrl('')?>');
			MyIndo.setSiteUrl('<?php echo $this->url()?>');
			MyIndo.setNameSpace('MyProject');
			MyIndo.setAuthKey('<?php echo $this->authKey?>');
			// window.onbeforeunload = function() {
			//     return "Are you sure you want to navigate away?";
			// }
		</script>
		<!-- End of : JS -->
	</head>
	<body>
		<?php echo $this->layout()->content . "\n"; ?>
	</body>
</html>