CREATE VIEW MS_PROVINCE_VIEW AS
SELECT
 msprv.ID,
 msprv.COUNTRY_ID,
 msctr.NAME as COUNTRY_NAME,
 msprv.NAME,
 msprv.CREATED_DATE,
 msprv.MODIFIED_DATE
FROM
 MS_PROVINCE msprv,
 MS_COUNTRY msctr
WHERE
 msprv.COUNTRY_ID = msctr.ID