CREATE VIEW `TR_TRAINING_PARTICIPANTS_VIEW` AS
SELECT
 TR_TRAINING_PARTICIPANTS.ID,
 TR_TRAINING_PARTICIPANTS.TRAINING_ID,
 MS_TRAININGS.NAME as `TRAINING_NAME`,

 /* MS_PARTICIPANTS */
 MS_PARTICIPANTS.ID as `PARTICIPANT_ID`,
 concat(`MS_PARTICIPANTS`.`FNAME`,' ',`MS_PARTICIPANTS`.`MNAME`,' ',`MS_PARTICIPANTS`.`LNAME`) AS `PARTICIPANT_NAME`,
 MS_PARTICIPANTS.FNAME as `PARTICIPANT_FNAME`,
 MS_PARTICIPANTS.MNAME as `PARTICIPANT_MNAME`,
 MS_PARTICIPANTS.LNAME as `PARTICIPANT_LNAME`,
 MS_PARTICIPANTS.SNAME as `PARTICIPANT_SNAME`,
 MS_PARTICIPANTS.GENDER as `PARTICIPANT_GENDER`,
 MS_PARTICIPANTS.BDATE as `PARTICIPANT_BDATE`,
 MS_PARTICIPANTS.MOBILE_NO as `PARTICIPANT_MOBILE_NO`,
 MS_PARTICIPANTS.PHONE_NO as `PARTCIPANT_PHONE_NO`,
 MS_PARTICIPANTS.EMAIL1 as `PARTICIPANT_EMAIL1`,
 MS_PARTICIPANTS.EMAIL2 as `PARTICIPANT_EMAIL2`,
 MS_PARTICIPANTS.FB as `PARTICIPANT_FB`,
 MS_PARTICIPANTS.TWITTER as `PARTICIPANT_TWITTER`,

 MS_ORGANIZATIONS.ID as `ORGANIZATION_ID`,
 MS_ORGANIZATIONS.CITY_ID as `ORGANIZATION_CITY_ID`,
 MS_CITY.NAME as `ORGANIZATION_CITY_NAME`,
 MS_ORGANIZATIONS.PROVINCE_ID as `ORGANIZATION_PROVINCE_ID`,
 MS_PROVINCE.NAME as `ORGANIZATION_PROVINCE_NAME`,
 MS_ORGANIZATIONS.COUNTRY_ID as `ORGANIZATION_COUNTRY_ID`,
 MS_COUNTRY.NAME as `ORGANIZATION_COUNTRY_NAME`,
 MS_ORGANIZATIONS.NAME as `ORGANIZATION_NAME`,
 MS_ORGANIZATIONS.PHONE_NO1 as `ORGANIZATION_PHONE_NO1`,
 MS_ORGANIZATIONS.PHONE_NO2 as `ORGANIZATION_PHONE_NO2`,
 MS_ORGANIZATIONS.EMAIL1 as `ORGANIZATION_EMAIL1`,
 MS_ORGANIZATIONS.EMAIL2 as `ORGANIZATION_EMAIL2`,
 MS_ORGANIZATIONS.WEBSITE as `ORGANIZATION_WEBSITE`,
 MS_ORGANIZATIONS.ADDRESS as `ORGANIZATION_ADDRESS`,

 TR_TRAINING_PARTICIPANTS.POSITION_ID,
 MS_POSITIONS.NAME as `POSITION_NAME`,

 TR_TRAINING_PARTICIPANTS.PRE_TEST,
 TR_TRAINING_PARTICIPANTS.POST_TEST,
 TR_TRAINING_PARTICIPANTS.DIFF,
 TR_TRAINING_PARTICIPANTS.CREATED_DATE,
 TR_TRAINING_PARTICIPANTS.MODIFIED_DATE
from
  TR_TRAINING_PARTICIPANTS
  JOIN TR_TRAININGS ON (TR_TRAINING_PARTICIPANTS.TRAINING_ID = TR_TRAININGS.ID)
  JOIN MS_TRAININGS ON (TR_TRAININGS.TRAINING_ID = MS_TRAININGS.ID)
  JOIN MS_PARTICIPANTS ON (TR_TRAINING_PARTICIPANTS.PARTICIPANT_ID = MS_PARTICIPANTS.ID)
  JOIN MS_ORGANIZATIONS ON (TR_TRAINING_PARTICIPANTS.ORGANIZATION_ID = MS_ORGANIZATIONS.ID)
  JOIN MS_POSITIONS ON (TR_TRAINING_PARTICIPANTS.POSITION_ID = MS_POSITIONS.ID)
  JOIN MS_CITY ON (MS_ORGANIZATIONS.CITY_ID = MS_CITY.ID)
  JOIN MS_PROVINCE ON (MS_ORGANIZATIONS.PROVINCE_ID = MS_PROVINCE.ID)
  JOIN MS_COUNTRY ON (MS_ORGANIZATIONS.COUNTRY_ID = MS_COUNTRY.ID)