CREATE VIEW TR_TRAINING_TRAINERS_VIEW AS
SELECT
 TR_TRAINING_TRAINERS.ID AS `ID`,
 TR_TRAINING_TRAINERS.TRAINING_ID AS `TR_TRAININGS_ID`,
 TR_TRAINING_TRAINERS.TRAINER_ID AS `TRAINER_ID`,
 TR_TRAINING_TRAINERS.ROLE_ID AS `ROLE_ID`,
 TR_TRAINING_TRAINERS.CITY_ID AS `CITY_ID`,
 TR_TRAINING_TRAINERS.PROVINCE_ID AS `PROVINCE_ID`,
 TR_TRAINING_TRAINERS.COUNTRY_ID AS `COUNTRY_ID`,
 TR_TRAINING_TRAINERS.CV_NAME AS `CV_NAME`,
 TR_TRAINING_TRAINERS.CV_PATH AS `CV_PATH`,
 TR_TRAINING_TRAINERS.CV_MIME_TYPE AS `CV_MIME_TYPE`,
 TR_TRAINING_TRAINERS.CV_SIZE AS `CV_SIZE`,
 TR_TRAINING_TRAINERS.CREATED_DATE AS `CREATED_DATE`,
 TR_TRAINING_TRAINERS.MODIFIED_DATE AS `MODIFIED_DATE`,

 /* TR_TRAININGS */
 -- TR_TRAININGS.ID AS `TR_TRAININGS_ID`,
 TR_TRAININGS.USER_ID AS `TRAINING_USER_ID`,
 TR_TRAININGS.TRAINING_ID AS `TRAINING_ID`,
 TR_TRAININGS.AREA_LEVEL_ID AS `TRAINING_AREA_LEVEL_ID`,
 TR_TRAININGS.BENEFICIARIES_ID AS `TRAINING_BENEFICIARIES_ID`,
 TR_TRAININGS.FUNDING_SOURCE_ID AS `TRAINING_FUNDING_SOURCE_ID`,
 TR_TRAININGS.VENUE_ID AS `TRAINING_VENUE_ID`,
 TR_TRAININGS.ORGANIZATION_ID AS `TRAINING_ORGANIZATION_ID`,
 TR_TRAININGS.SDATE AS `TRAINING_SDATE`,
 TR_TRAININGS.EDATE AS `TRAINING_EDATE`,
 
 /* USERS */
 -- USERS.USER_ID AS `USER_ID`,
 USERS.USERNAME AS `USERNAME`,
 USERS.EMAIL AS `USER_EMAIL`,
 USERS.ACTIVE AS `USER_ACTIVE`,
 USERS.IP_ADDRESS AS `USER_IP_ADDRESS`,
 USERS.LAST_IP_ADDRESS AS `USER_LAST_IP_ADDRESS`,
 USERS.LAST_LOGIN AS `USER_LAST_LOGIN`,
 /* END OF : USERS */

 /* MS_TRAININGS */
 -- MS_TRAININGS.ID AS `MS_TRAININGS_ID`,
 MS_TRAININGS.NAME AS `TRAINING_NAME`,
 /* END OF : MS_TRAININGS */

 /* MS_AREA_LEVELS */
 -- MS_AREA_LEVELS.ID AS `MS_AREA_LEVELS_ID`,
 MS_AREA_LEVELS.NAME AS `TRAINING_AREA_LEVEL_NAME`,
 MS_AREA_LEVELS.TYPE AS `TRAINING_AREA_LEVEL_TYPE`,
 /* END OF : MS_AREA_LEVELS */

 /* MS_BENEFICIARIES */
 -- MS_BENEFICIARIES.ID AS `MS_BENEFICIARIES_ID`,
 MS_BENEFICIARIES.NAME AS `TRAINING_BENEFICIARIES_NAME`,
 /* END OF : MS_BENEFICIARIES */

 /* MS_FUNDING_SOURCES */
 -- MS_FUNDING_SOURCES.ID AS `MS_FUNDING_SOURCES_ID`,
 MS_FUNDING_SOURCES.CITY_ID AS `TRAINING_FUNDING_SOURCE_CITY_ID`,
 -- CITYFS.NAME AS `TRAINING_FUNDING_SOURCE_CITY_NAME`,
 MS_FUNDING_SOURCES.PROVINCE_ID AS `TRAINING_FUNDING_SOURCE_PROVINCE_ID`,
 -- PROVINCEFS.NAME AS `TRAINING_FUNDING_SOURCE_PROVINCE_NAME`,
 MS_FUNDING_SOURCES.COUNTRY_ID AS `TRAINING_FUNDING_SOURCE_COUNTRY_ID`,
 -- COUNTRYFS.NAME AS `TRAINING_FUNDING_SOURCE_COUNTRY_NAME`,
 MS_FUNDING_SOURCES.NAME AS `TRAINING_FUNDING_SOURCE_NAME`,
 MS_FUNDING_SOURCES.PHONE_NO1 AS `TRAINING_FUNDING_SOURCE_PHONE_NO1`,
 MS_FUNDING_SOURCES.PHONE_NO2 AS `TRAINING_FUNDING_SOURCE_PHONE_NO2`,
 MS_FUNDING_SOURCES.EMAIL1 AS `TRAINING_FUNDING_SOURCE_EMAIL1`,
 MS_FUNDING_SOURCES.EMAIL2 AS `TRAINING_FUNDING_SOURCE_EMAIL2`,
 MS_FUNDING_SOURCES.WEBSITE AS `TRAINNG_FUNDING_SOURCE_WEBSITE`,
 MS_FUNDING_SOURCES.ADDRESS AS `TRAINING_FUNDING_SOURCE_ADDRESS`,
 /* END OF : MS_FUNDING_SOURCES */

 /* MS_VENUE */
 -- MS_VENUES.ID AS `TRAINING_VENUE_ID`,
 MS_VENUES.CITY_ID AS `TRAINING_VENUE_CITY_ID`,
 -- CITYVE.NAME AS `TRAINING_VENUE_CITY_NAME`,
 MS_VENUES.PROVINCE_ID AS `TRAINING_VENUE_PROVINCE_ID`,
 -- PROVINCEVE.NAME AS `TRAINING_VENUE_PROVINCE_NAME`,
 MS_VENUES.COUNTRY_ID AS `TRAINING_VENUE_COUNTRY_ID`,
 -- COUNTRYVE.NAME AS `TRAINING_VENUE_COUNTRY_NAME`,
 MS_VENUES.NAME AS `TRAINING_VENUE_NAME`,
 MS_VENUES.PHONE_NO1 AS `TRAINING_VENUE_PHONE_NO1`,
 MS_VENUES.PHONE_NO2 AS `TRAINING_VENUE_PHONE_NO2`,
 MS_VENUES.EMAIL1 AS `TRAINING_VENUE_EMAIL1`,
 MS_VENUES.EMAIL2 AS `TRAINING_VENUE_EMAIL2`,
 MS_VENUES.WEBSITE AS `TRAINING_VENUE_WEBSITE`,
 MS_VENUES.ADDRESS AS `TRAINING_VENUE_ADDRESS`,
 /* END OF : MS_VENUE */

 /* MS_ORGANIZATIONS */
 MS_ORGANIZATIONS.CITY_ID AS `TRAINING_ORGANIZATION_CITY_ID`,
 -- CITYOR.NAME AS `TRAINING_ORGANIZATION_CITY_NAME`,
 MS_ORGANIZATIONS.PROVINCE_ID AS `TRAINING_ORGANIZATION_PROVINCE_ID`,
 -- PROVINCEOR.NAME AS `TRAINING_ORGANIZATION_PROVINCE_NAME`,
 MS_ORGANIZATIONS.COUNTRY_ID AS `TRAINING_ORGANIZATION_COUNTRY_ID`,
 -- COUNTRYOR.NAME AS `TRAINING_ORGANIZATION_COUNTRY_NAME`,
 MS_ORGANIZATIONS.NAME AS `TRAINING_ORGANIZATION_NAME`,
 MS_ORGANIZATIONS.PHONE_NO1 AS `TRAINING_ORGANIZATION_PHONE_NO1`,
 MS_ORGANIZATIONS.PHONE_NO2 AS `TRAINING_ORGANIZATION_PHONE_NO2`,
 MS_ORGANIZATIONS.EMAIL1 AS `TRAINING_ORGANIZATION_EMAIL1`,
 MS_ORGANIZATIONS.EMAIL2 AS `TRAINING_ORGANIZATION_EMAIL2`,
 MS_ORGANIZATIONS.WEBSITE AS `TRAINING_ORGANIZATION_WEBSITE`,
 MS_ORGANIZATIONS.ADDRESS AS `TRAINING_ORGANIZATION_ADDRESS`,
 /* END OF : MS_ORGANIZATIONS */
 /* END OF : TR_TRAININGS */

 /* MS_CITY */
 -- MS_CITY.ID AS `TRAINER_CITY_ID`
 CITYTR.NAME AS `CITY_NAME`,
 /* END OF : MS_CITY */

 /* MS_PROVINCE */
 PROVINCETR.NAME AS `PROVINCE_NAME`,
 /* END OF : MS_PROVINCE */

 /* MS_COUNTRY */
 COUNTRYTR.NAME AS `COUNTRY_NAME`,
 /* END OF : MS_COUNTRY */

 /* MS_TRAINERS */
 -- MS_TRAINERS.ID AS `TRAINER_ID`,
 MS_TRAINERS.NAME AS `TRAINER_NAME`,
 MS_TRAINERS.NICKNAME AS `TRAINER_NICKNAME`,
 MS_TRAINERS.GENDER AS `TRAINER_GENDER`,
 MS_TRAINERS.ADDRESS AS `TRAINER_ADDRESS`,
 MS_TRAINERS.BDATE AS `TRAINER_BDATE`,
 MS_TRAINERS.MOBILE_NO AS `TRAINER_MOBILE_NO`,
 MS_TRAINERS.PHONE_NO AS `TRAINER_PHONE_NO`,
 MS_TRAINERS.EMAIL1 AS `TRAINER_EMAIL1`,
 MS_TRAINERS.EMAIL2 AS `TRAINER_EMAIL2`,
 MS_TRAINERS.FB AS `TRAINER_FB`,
 MS_TRAINERS.TWITTER AS `TRAINER_TWITTER`,
 /* END OF : MS_TRAINERS */

 /* MS_ROLES */
 -- MS_ROLES.ID AS `TRAINER_ROLE_ID`
 MS_ROLES.NAME AS `ROLE_NAME`
 /* END OF : MS_ROLES */
FROM
 TR_TRAINING_TRAINERS
 JOIN
 TR_TRAININGS ON TR_TRAINING_TRAINERS.TRAINING_ID = TR_TRAININGS.ID
 JOIN
 USERS ON TR_TRAININGS.USER_ID = USERS.USER_ID
 JOIN
 MS_TRAININGS ON TR_TRAININGS.TRAINING_ID = MS_TRAININGS.ID
 JOIN
 MS_AREA_LEVELS ON TR_TRAININGS.AREA_LEVEL_ID = MS_AREA_LEVELS.ID
 JOIN
 MS_BENEFICIARIES ON TR_TRAININGS.BENEFICIARIES_ID = MS_BENEFICIARIES.ID
 JOIN
 MS_FUNDING_SOURCES ON TR_TRAININGS.FUNDING_SOURCE_ID = MS_FUNDING_SOURCES.ID 
 	-- JOIN MS_CITY CITYFS ON MS_FUNDING_SOURCES.CITY_ID = CITYFS.ID
 	-- JOIN MS_PROVINCE PROVINCEFS ON MS_FUNDING_SOURCES.PROVINCE_ID = PROVINCEFS.ID
 	-- JOIN MS_COUNTRY COUNTRYFS ON MS_FUNDING_SOURCES.COUNTRY_ID = COUNTRYFS.ID
 JOIN
 MS_VENUES ON TR_TRAININGS.VENUE_ID = MS_VENUES.ID
 	-- JOIN MS_CITY CITYVE ON MS_VENUES.CITY_ID = CITYVE.ID
 	-- JOIN MS_PROVINCE PROVINCEVE ON MS_VENUES.PROVINCE_ID = PROVINCEVE.ID
 	-- JOIN MS_COUNTRY COUNTRYVE ON MS_VENUES.COUNTRY_ID = COUNTRYVE.ID
 JOIN
 MS_ORGANIZATIONS ON TR_TRAININGS.ORGANIZATION_ID = MS_ORGANIZATIONS.ID
 	-- JOIN MS_CITY CITYOR ON MS_ORGANIZATIONS.CITY_ID = CITYOR.ID
 	-- JOIN MS_PROVINCE PROVINCEOR ON MS_ORGANIZATIONS.PROVINCE_ID = PROVINCEOR.ID
 	-- JOIN MS_COUNTRY COUNTRYOR ON MS_ORGANIZATIONS.COUNTRY_ID = COUNTRYOR.ID
 JOIN
 MS_CITY CITYTR ON TR_TRAINING_TRAINERS.CITY_ID = CITYTR.ID
 JOIN
 MS_PROVINCE PROVINCETR ON TR_TRAINING_TRAINERS.PROVINCE_ID = PROVINCETR.ID
 JOIN
 MS_COUNTRY COUNTRYTR ON TR_TRAINING_TRAINERS.COUNTRY_ID = COUNTRYTR.ID
 JOIN
 MS_TRAINERS ON TR_TRAINING_TRAINERS.TRAINER_ID = MS_TRAINERS.ID
 JOIN
 MS_ROLES ON TR_TRAINING_TRAINERS.ROLE_ID = MS_ROLES.ID