create view TR_TRAINING_PARTICIPANTS_VIEW as
select
 trtrprt.ID,
 trtrprt.TRAINING_ID,
 mstr.TRAINING_NAME as TRAINING_NAME,
 trtrprt.PARTICIPANT_ID,
 mspr.NAME as PARTICIPANT_NAME,
 mspr.FNAME as PARTICIPANT_FNAME,
 mspr.MNAME as PARTICIPANT_MNAME,
 mspr.LNAME as PARTICIPANT_LNAME,
 mspr.SNAME as PARTICIPANT_SNAME,
 mspr.GENDER as PARTICIPANT_GENDER,
 mspr.BDATE as PARTICIPANT_BDATE,
 mspr.MOBILE_NO as PARTICIPANT_MOBILE_NO,
 mspr.PHONE_NO as PARTCIPANT_PHONE_NO,
 mspr.EMAIL1 as PARTICIPANT_EMAIL1,
 mspr.EMAIL2 as PARTICIPANT_EMAIL2,
 mspr.FB as PARTICIPANT_FB,
 mspr.TWITTER as PARTICIPANT_TWITTER,
 trtrprt.ORGANIZATION_ID,
 msor.CITY_ID as ORGANIZATION_CITY_ID,
 msor.CITY_NAME as ORGANIZATION_CITY_NAME,
 msor.PROVINCE_ID as ORGANIZATION_PROVINCE_ID,
 msor.PROVINCE_NAME as ORGANIZATION_PROVINCE_NAME,
 msor.COUNTRY_ID as ORGANIZATION_COUNTRY_ID,
 msor.COUNTRY_NAME as ORGANIZATION_COUNTRY_NAME,
 msor.NAME as ORGANIZATION_NAME,
 msor.PHONE_NO1 as ORGANIZATION_PHONE_NO1,
 msor.PHONE_NO2 as ORGANIZATION_PHONE_NO2,
 msor.EMAIL1 as ORGANIZATION_EMAIL1,
 msor.EMAIL2 as ORGANIZATION_EMAIL2,
 msor.WEBSITE as ORGANIZATION_WEBSITE,
 msor.ADDRESS as ORGANIZATION_ADDRESS,
 trtrprt.POSITION_ID,
 mspo.NAME as POSITION_NAME,
 trtrprt.PRE_TEST,
 trtrprt.POST_TEST,
 trtrprt.DIFF,
 trtrprt.CREATED_DATE,
 trtrprt.MODIFIED_DATE
from
 TR_TRAINING_PARTICIPANTS trtrprt,
 TR_TRAININGS_VIEW mstr,
 MS_PARTICIPANTS_VIEW mspr,
 MS_ORGANIZATIONS_VIEW msor,
 MS_POSITIONS mspo
where
 trtrprt.TRAINING_ID = mstr.ID and
 trtrprt.TRAINING_ID = mstr.ID and
 trtrprt.PARTICIPANT_ID = mspr.ID and
 trtrprt.ORGANIZATION_ID = msor.ID and
 trtrprt.POSITION_ID = mspo.ID