SELECT
 TR_TRAINING_PARTICIPANTS.ID AS `ID`,
 TR_TRAINING_PARTICIPANTS.TRAINING_ID AS `TRAINING_ID`,
 TR_TRAINING_PARTICIPANTS.PARTICIPANT_ID AS `PARTICIPANT_ID`,
 TR_TRAINING_PARTICIPANTS.ORGANIZATION_ID AS `ORGANIZATION_ID`,
 TR_TRAINING_PARTICIPANTS.POSITION_ID AS `POSITION_ID`,
 TR_TRAINING_PARTICIPANTS.PRE_TEST AS `PRE_TEST`,
 TR_TRAINING_PARTICIPANTS.POST_TEST AS `POST_TEST`,
 TR_TRAINING_PARTICIPANTS.DIFF AS `DIFF`,
 TR_TRAINING_PARTICIPANTS.CREATED_DATE `CREATED_DATE`,
 TR_TRAINING_PARTICIPANTS.MODIFIED_DATE `MODIFIED_DATE`
FROM
 TR_TRAINING_PARTICIPANTS